// MANAGE NOTIFIACATION
export const IS_LOADING = 'IS_LOADING';
export const IS_PENDING_ACTION = 'IS_PENDING_ACTION';
export const IS_LOADING_ZONE = 'IS_LOADING_ZONE';
export const IS_LOADING_CHAT = 'IS_LOADING_CHAT';
export const IS_PIN_APPROUVED = 'IS_PIN_APPROUVED';
export const IS_LOADING_LINK = 'IS_LOADING_LINK';
export const IS_NETWORK = 'IS_NETWORK';
export const INFO_NETWORK = 'INFO_NETWORK';

// MANAGE NAVIGATION
export const IS_HEADER = 'IS_HEADER';
export const PAGE_TITLE = 'PAGE_TITLE';
export const ROOT_NAVIGATION = 'ROOT_NAVIGATION';
export const IS_VISIBLE_POST = 'IS_VISIBLE_POST';

// MANAGE AUTHENTIFICATION
export const USER_INFOS = 'USER_INFOS'; 
export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
export const USER_TOKEN = 'USER_TOKEN';
export const AUTH_ERROR_MESSAGE = 'AUTH_ERROR_MESSAGE';
export const IS_AUTH_ERROR = 'IS_AUTH_ERROR';
export const SITE_INFOS = 'SITE_INFOS';

//MANAGE NOTIFICATION
export const IS_ALERT = 'IS_ALERT';
export const ALERT_TYPE = 'ALERT_TYPE';
export const ALERT_TITLE = 'ALERT_TITLE';
export const ALERT_SUBTITLE = 'ALERT_SUBTITLE';
export const ALERT_CONFIRM = 'ALERT_CONFIRM';
export const ALERT_CANCEL = 'ALERT_CANCEL';
export const COUNT_NEW_NOTIFICATION = 'COUNT_NEW_NOTIFICATION';
export const COUNT_NEW_MESSAGE = 'COUNT_NEW_MESSAGE';

//transaction
export const LAST_TRANSACTION = 'LAST_TRANSACTION';